import Head from "next/head";
import Navbar from "../components/organisms/Navbar";
import StoreLeadingContent from "@/components/organisms/StoreLeadingContent";

export default function Home() {
  return (
    <>
      <Head>
        <title>Theanknowartist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <StoreLeadingContent />

      {/* Welcome to ruby market place */}
    </>
  );
}
